spring:
  h2:
    console:
      enabled:  true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#    This will mess up bean creation when not define properly
#  datasource:
#    url: jdbc:h2:mem:testdb
  security:
    user:
      name: sa
  jackson:
    serialization:
      indent_output: true

server:
  error:
    whitelabel:
      enabled: false
    path: /error